spring:
  profiles.include: 'secrets'
  datasource:
    driver-class: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://mariadb.fabioplunser.com/swa"

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    static-path-pattern: '/**'

  resources:
    static-locations: 'classpath:/static/'

server:
  port: 3000
