
server:
  port: 3000

spring:
  profiles.include: 'secrets'
  datasource:
    driver-class: org.mariadb.jdbc.Driver
    # url: "jdbc:mariadb://mariadb.fabioplunser.com/swa"
    url: "jdbc:mariadb://localhost/swa"
  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    static-path-pattern: '/**'

  resources:
    static-locations: 'classpath:/static/'

  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: password
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true