
server:
  port: 3000
  servlet:
    context-path: /

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  profiles:
    active: 'prod'
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false

  # profiles:
  #     active: 'prod'
  # profiles.include: 'secrets'
  # datasource:
  #   driver-class: org.mariadb.jdbc.Driver
  #   url: "jdbc:mariadb://localhost/swa"
  # jpa:
  #   hibernate:
  #     ddl-auto: create

  mvc:
    static-path-pattern: '/**'

  resources:
    static-locations: 'classpath:/static/'

  mail:
    host: mail.gmx.net
    port: 587
    username: simpson-lisa@gmx.at
    password: p1a2s3s4!
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true