
server:
  port: 3000
  servlet:
    context-path: /

springdoc:
  # API-Docs is an Endpoint where the Swagger-UI
  # gets the information about the Endpoints.
  api-docs:
    path: /api-docs
    # TODO: Only enable OpenAPI/Swagger in Development Environment
    enabled: true
  swagger-ui:
    path: /swagger
    # TODO: Only enable OpenAPI/Swagger in Development Environment
    enabled: true

spring:
  # profiles.include: 'secrets'
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'
    # driver-class: org.mariadb.jdbc.Driver
    # url: "jdbc:mariadb://mariadb.fabioplunser.com/swa"
  jpa:
    hibernate:
      ddl-auto: create

  mvc:
    static-path-pattern: '/**'

  resources:
    static-locations: 'classpath:/static/'

  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: password
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true