
server:
  port: 3000
  servlet:
    context-path: /

spring:
  datasource:
    # Use an in-memory Database for testing
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
