
swa:
  token:
    expiration-duration: 1d
  admin:
    base: /src/admin
  api:
    base: /api
  error:
    base: /error

server:
  port: 3000
  servlet:
    context-path: /

logging:
  level:
    web: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  # profiles:
  #   active: 'prod'
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: 'jdbc:h2:mem:testdb'
  # jpa:
  #   hibernate:
  #     ddl-auto: create
  # h2:
  #   console:
  #     enabled: false

  profiles:
      active: 'prod'
      include: 'secrets'
  datasource:
    driver-class: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost/swa"
  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    static-path-pattern: '/**'

  resources:
    static-locations: 'classpath:/static/'

  mail:
    host: mail.gmx.net
    port: 587
    username: simpson-lisa@gmx.at
    password: p1a2s3s4!
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true